name: Run API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Newman via Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/postman:/etc/newman" \
            postman/newman:alpine \
            run collection.json \
            --environment=environment.json \
            --insecure \
            --reporters cli,json,html \
            --reporter-json-export=newman-report.json \
            --reporter-html-export=newman-report.html
      
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: newman-reports
          path: postman/