services:
  db:
    image: postgis/postgis:15-3.5  # Postgres 15 with PostGIS 3.5
    container_name: fastabiz_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fastabiz_db
    ports: # migration purposes
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fastabiz_db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports: #postman access
    - "8080:8080"
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      # test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
  
  kong:
    image: kong:3.5
    depends_on:
      backend:
        condition: service_healthy   
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_LISTEN: 127.0.0.1:8001  # Bind Admin API to loopback inside the container - localhost only
    ports:
      - "8000:8000"  # Public proxy
    volumes:  
      - ./kong/kong.yml:/etc/kong/kong.yml:ro
    # restart: always

  # caddy:
  #   image: caddy:2
  #   depends_on:
  #     - kong
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile:ro
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   restart: always

volumes:
  pgdata:
  # caddy_data:
  # caddy_config:
