services:
  db:
    image: postgres:15
    container_name: logistics_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: logistics_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: logistics_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
